### ISSUE TITLE
Checklist of Issues

### ISSUE THREAD

**Issue by KBoothMidd** [KBoothMidd/skills-communicate-using-markdown#2]
- [ ] See a checklist in the Issue Tab
- [ ] Can I get more checklists
- [x] And maybe some are complete
